### ISSUE TITLE
Test Eth2 migration in network gnosis

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodePackage-gnosis-beacon-chain-prysm#15]
**Test instructions**

Having at least 2 validators in the legacy Prysm-gnosis (previous version to v1.0.0) and web3signer-gnosis already installed, manually update Prysm-gnosis to the latest version.

During container start-up, there should be some logs saying "found validators, starting migration". This process will export your validator keystores, walletpassword, and slashing protection data to the web3signer via the remote keymanager API.

If there is any error during this migration, the volume will be empty, ensuring no keystores are loaded in the Prysm-gnosis.

Ensure this process was successfully and the keystores are loaded in the web3signer

**Test report**

With an editable unique comment report any errors and feedback you may find necessary.

If no errors leave a checkmark

**Testers**

@pablomendezroyo
@3alpha
@tropicar
@mgarciate

**Comment by Pol-Lanski** [comment]
@alexpeterson91 @3alpha @tropicar @mgarciate can we do the testing and leave a comment here ASAP?

**Comment by Pol-Lanski** [comment]
## Test 1:

### Previous: 
- Gnosis Beacon Chain Prysm Validator running with 4 validators. Validating fine. 

### Testing steps:
1. Installed Web3Signer Gnosis Chain.
2. Installed Gnosis Beacon Chain Prysm

Immediately after, validator stops validating, beacon chain keeps crashing and restarting:

<img width="1262" alt="Screenshot 2022-06-20 at 16 15 06" src="https://user-images.githubusercontent.com/19168735/174610022-8ac7dc63-b32b-4207-8c64-e66b0d4ac1c1.png">

<img width="938" alt="Screenshot 2022-06-20 at 16 16 27" src="https://user-images.githubusercontent.com/19168735/174610089-17ffa00e-12af-4685-ac16-ab27df083340.png">


```
time="2022-06-20 13:15:08" level=info msg="Created validator cache" elapsed=255.786µs prefix=db
time="2022-06-20 13:15:08" level=info msg="Updating DB and creating buckets..." prefix=db
time="2022-06-20 13:15:08" level=info msg="Updated db and created buckets" elapsed=9.596476ms prefix=db
time="2022-06-20 13:15:08" level=info msg="requesting https://rpc-gbc.gnosischain.com/eth/v2/debug/beacon/states/genesis"
time="2022-06-20 13:15:11" level=info msg="requesting https://rpc-gbc.gnosischain.com/eth/v1/beacon/weak_subjectivity"
time="2022-06-20 13:15:11" level=info msg="falling back to generic checkpoint derivation, weak_subjectivity API not supported by server"
time="2022-06-20 13:15:11" level=info msg="requesting https://rpc-gbc.gnosischain.com/eth/v1/node/version"
time="2022-06-20 13:15:11" level=info msg="requesting https://rpc-gbc.gnosischain.com/eth/v2/debug/beacon/states/head"
time="2022-06-20 13:15:13" level=error msg="Error retrieving checkpoint origin state and block: error computing weak subjectivity epoch via head state inspection: error detecting chain config for beacon state: version=0x01000064: version not found in fork version schedule for any known config" prefix=main
time="2022-06-20 13:16:14" level=warning msg="Running on Ethereum Consensus Mainnet" prefix=flags
time="2022-06-20 13:16:14" level=info msg="Checking DB" database-path="/data/beaconchaindata" prefix=node
time="2022-06-20 13:16:14" level=info msg="Opening Bolt DB at /data/beaconchaindata/beaconchain.db" prefix=db
time="2022-06-20 13:16:14" level=info msg="Opened Bolt DB" elapsed=52.655641ms prefix=db
time="2022-06-20 13:16:14" level=info msg="Creating block cache..." prefix=db
time="2022-06-20 13:16:14" level=info msg="Created block cache" elapsed=173.389µs prefix=db
time="2022-06-20 13:16:14" level=info msg="Creating validator cache..." prefix=db
time="2022-06-20 13:16:14" level=info msg="Created validator cache" elapsed=3.877257ms prefix=db
time="2022-06-20 13:16:14" level=info msg="Updating DB and creating buckets..." prefix=db
time="2022-06-20 13:16:14" level=info msg="Updated db and created buckets" elapsed=9.404374ms prefix=db
time="2022-06-20 13:16:14" level=info msg="requesting https://rpc-gbc.gnosischain.com/eth/v2/debug/beacon/states/genesis"
time="2022-06-20 13:16:15" level=info msg="requesting https://rpc-gbc.gnosischain.com/eth/v1/beacon/weak_subjectivity"
time="2022-06-20 13:16:15" level=info msg="falling back to generic checkpoint derivation, weak_subjectivity API not supported by server"
time="2022-06-20 13:16:15" level=info msg="requesting https://rpc-gbc.gnosischain.com/eth/v1/node/version"
time="2022-06-20 13:16:16" level=info msg="requesting https://rpc-gbc.gnosischain.com/eth/v2/debug/beacon/states/head"
```

**Comment by Pol-Lanski** [comment]
## Test 2:

- Rewinded my system to the initial state: validating with current Prysm and no web3signer

### Testing Steps:
- Installed web3signer
- Installed prysm

## Results:
**Not validating**

Web3Signer Logs:
```
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
2022-06-21 09:08:46.252+00:00 | main | INFO  | Web3SignerApp | Web3Signer has started with args --key-store-path=/opt/web3signer/keyfiles,--http-listen-port=9000,--http-listen-host=0.0.0.0,--http-host-allowlist=web3signer.web3signer-gnosis.dappnode,web3signer.web3signer-gnosis.dappnode,validator.teku-gnosis.dappnode,--http-cors-origins=*,--metrics-enabled=true,--metrics-host,0.0.0.0,--metrics-port,9091,--metrics-host-allowlist=*,eth2,--network=gnosis,--slashing-protection-db-url=jdbc:postgresql://postgres.web3signer-gnosis.dappnode:5432/web3signer-gnosis,--slashing-protection-db-username=postgres,--slashing-protection-db-password=gnosis,--key-manager-api-enabled=true
2022-06-21 09:08:46.257+00:00 | main | INFO  | Web3SignerApp | Version = web3signer/v22.5.1/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17
2022-06-21 09:08:47.154+00:00 | main | INFO  | HikariDataSource | HikariPool-1 - Starting...
2022-06-21 09:08:47.294+00:00 | main | INFO  | HikariDataSource | HikariPool-1 - Start completed.
ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.9.3
ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.9.3
ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.9.3
ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.9.3
2022-06-21 09:08:47.480+00:00 | main | INFO  | HikariDataSource | HikariPool-2 - Starting...
2022-06-21 09:08:47.501+00:00 | main | INFO  | HikariDataSource | HikariPool-2 - Start completed.
2022-06-21 09:08:47.708+00:00 | main | INFO  | MetricsHttpService | Starting metrics http service on 0.0.0.0:9091
2022-06-21 09:08:47.792+00:00 | vert.x-eventloop-thread-0 | INFO  | MetricsHttpService | Metrics service started and listening on 0.0.0.0:9091
2022-06-21 09:08:47.810+00:00 | pool-2-thread-1 | INFO  | SignerLoader | Loading signer configuration metadata files from /opt/web3signer/keyfiles
2022-06-21 09:08:47.815+00:00 | pool-2-thread-1 | INFO  | SignerLoader | Signer configuration metadata files read in memory 0 in 00:00:00.002
2022-06-21 09:08:47.816+00:00 | ForkJoinPool-1-worker-1 | INFO  | SignerLoader | Parsing configuration metadata files
2022-06-21 09:08:47.817+00:00 | ForkJoinPool-1-worker-1 | INFO  | SignerLoader | Total configuration metadata files processed: 0
2022-06-21 09:08:47.817+00:00 | ForkJoinPool-1-worker-1 | INFO  | SignerLoader | Total signers loaded from configuration files: 0 in 00:00:00.001
2022-06-21 09:08:47.820+00:00 | pool-2-thread-1 | WARN  | Eth2Runner | No BLS keys loaded. Check that the key store has BLS key config files
2022-06-21 09:08:47.823+00:00 | pool-2-thread-1 | INFO  | DefaultArtifactSignerProvider | Total signers (keys) currently loaded in memory: 0
2022-06-21 09:08:48.319+00:00 | main | INFO  | Runner | Web3Signer has started with TLS disabled, and ready to handle signing requests on 0.0.0.0:9000
[ WARN ] beacon-chain is not available, make sure the server is listening: , HTTP code 000
[ WARN ] beacon-chain is not available, make sure the server is listening: , HTTP code 000
[ WARN ] beacon-chain is not available, make sure the server is listening: , HTTP code 000
[ WARN ] beacon-chain is not available, make sure the server is listening: , HTTP code 000
[ WARN ] beacon-chain is not available, make sure the server is listening: , HTTP code 000
[ WARN ] beacon-chain is not available, make sure the server is listening: , HTTP code 000
```

TBH, I failed this on purpose. It let me install the web3signer with Teku as the client, so when I upgraded to the new version of Prysm, the web3signer was probably not listening to the Prysm client and did not receive the keys. 

Result: Keys destroyed, no validation, no successful migration.

Question: What are we going to do to avoid this to happen to a user?

**Comment by Pol-Lanski** [comment]
# Test 3:

Starting with 
- Gnosis Chain Prysm - Version: 0.1.8 (v2.1.2-gbc upstream)
- core.dnp.dappnode.eth: 0.2.55

Update dappnode to v0.2.56 ([/ipfs/QmPa5i1SwFdno9B2bT9fVXsMXWSRAuyawng1VQfk3n75Tw](http://my.dappnode/#/installer/%2Fipfs%2FQmPa5i1SwFdno9B2bT9fVXsMXWSRAuyawng1VQfk3n75Tw)

| STEP + Package  | Version  | HASH    | Expected Result   | Result  | 
| --------------- | -------- | ------- | ------     | ------  |
| 1. Install Teku       | v0.1.0 | [QmWdNHTCUPok4C6dt5FuQxE11gxbatXarRBhpJpEaSRCWD](http://my.dappnode/#/installer/%2Fipfs%2FQmWdNHTCUPok4C6dt5FuQxE11gxbatXarRBhpJpEaSRCWD)  | ❌ NOT Able to install | ✅  NOT ABLE TO INSTALL! |
| 2. Install Lighthouse | v0.1.0 | [QmQcvjJri4XEzh4169pg6q6oDnN8eKBf7dKFnamrdMkcbu](http://my.dappnode/#/installer/%2Fipfs%2FQmQcvjJri4XEzh4169pg6q6oDnN8eKBf7dKFnamrdMkcbu) | ❌ NOT Able to install | ✅ NOT ABLE TO INSTALL!  |
| 3. Install Web3Signer | v0.1.2 | [web3signer-gnosis.dnp.dappnode.eth](http://my.dappnode/#/installer/web3signer-gnosis.dnp.dappnode.eth)  | ❌ NOT Able to install | ✅ NOT ABLE TO INSTALL |
| 4. Install Prysm      | v1.0.0 | [QmRpYK5N84V7LPyZmsjPB2TmLSPiuyPWV5DHbhoqSbtSNh](http://my.dappnode/#/installer/%2Fipfs%2FQmRpYK5N84V7LPyZmsjPB2TmLSPiuyPWV5DHbhoqSbtSNh) | ✅  Able to install | ✅ ABLE TO INSTALL |
| 5. Check Prysm      | v1.0.0 | -  | All keys migrated | ✅  Keys migrated  |
| 6. Check Web3Signer | v1.0.2 | -  | All keys migrated, get into web3signer UI | ✅ Keys migrated in Web3signer  |
| 7. Install Teku       | v0.1.0 | [QmWdNHTCUPok4C6dt5FuQxE11gxbatXarRBhpJpEaSRCWD](http://my.dappnode/#/installer/%2Fipfs%2FQmWdNHTCUPok4C6dt5FuQxE11gxbatXarRBhpJpEaSRCWD)   | ✅ Able to install | ✅ ABLE TO INSTALL |
| 8. Install Lighthouse | v0.1.0 | [QmQcvjJri4XEzh4169pg6q6oDnN8eKBf7dKFnamrdMkcbu](http://my.dappnode/#/installer/%2Fipfs%2FQmQcvjJri4XEzh4169pg6q6oDnN8eKBf7dKFnamrdMkcbu)  | ✅ Able to install | ✅ / ❌  |
| 10. Switch client in Web3Signer | v1.0.2 | -  | Continue validating switching client | ✅ Teku, Prysm, Lighthouse  |
| 11. Switch client in Web3Signer | v1.0.2 | -  | pubkeys were removed on previous client* | ✅ Prysm -> Teku; Teku -> Lighthouse (not installed); Prysm -> Lighthouse; Lighthouse -> Teku; Teku -> Prysm  |
| 12. Switch client in Web3Signer to a client not installed | v1.0.2 | -  | notification on the top right corner* | ✅ Notification received and also TG  |

As an extra: When I selected `teku` installing web3signer, knowing that teku wasn't installed, the migration happened anyway (yay, didn't lose keys!) and the telegram bot started spamming me that I don't have Teku installed. If I were a user with the TG bot configured I would immediately know what's wrong and would have been able to correct it. Nice.

When switching to a client that is not installed, same notification in telegram and also it removed pubkeys from the client.

Every time web3signer restarts, this pops up. Is it concerning?
```
ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.9.3
ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.9.3
ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.9.3
ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.9.3
```
