### ISSUE TITLE
Test validation user onboarding in network gnosis

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodePackage-gnosis-beacon-chain-prysm#16]
**Test instructions**

Your role will be to become a new user about to start validating in gnosis with the web3signer. Having installed web3signer-gnosis + client test the onboarding process to start validating. 

**Test report**

With an editable unique comment report any errors and feedback you may find necessary.

If no errors leave a checkmark

**Testers**

@pablomendezroyo
@3alpha
@tropicar
@mgarciate

**Comment by alexpeterson91** [comment]
Gonna close this since it's now done correct?
