### ISSUE TITLE
Add fallback-web3-provider field as optional environment variable

### ISSUE THREAD

**Issue by tropicar** [dappnode/DAppNodePackage-gnosis-beacon-chain-prysm#18]
**Is your feature request related to a problem? Please describe.**

The fallback-web3-provider flag is very important and it can help a lot of the users, to create an optional environment variable can make it easier to be aware to the users this option exists and make it easy to set up. 

**Describe the solution you'd like**

In the entrypoint.sh of the beacon-chain service, add a little if-else condition that checks if the user has filled that field and add the flag in consequence

**Describe alternatives you've considered**

Make this option mandatory. Maybe we could add this step as mandatory at some point.

**Comment by alexpeterson91** [comment]
Should I be closing this now since this has been implemented in all gnosis clients now correct?

**Comment by pablomendezroyo** [comment]
yes!
