### ISSUE TITLE
Fix Grafana dashboard

### ISSUE THREAD

**Issue by mgarciate** [dappnode/DAppNodePackage-Gnosis-Beacon-Chain-Prysm#4]

**Comment by alexpeterson91** [comment]
@mgarciate again like the other issue i opened about grafana reporting prysm mainnet and prater beacon chain and validator combined this new package is now also combined with them, i have a sharp increase CPU usage in beaconchain as soon as i installed the GBC on one of my test servers and grafana continues to keep showing any prysm related package as being 1
